version: "2.1"
services:
  univariate:
    image: theinnovativesolution/visualisation_univariate:latest-dev
    container_name: univariate
    command: "gunicorn -w 4 -b 0.0.0.0:8050 app:server"
    restart: always
    ports:
      - "8050:8050"
    networks:
      - visualisation
  multivariate:
    image: theinnovativesolution/visualisation_multivariate:latest-dev
    container_name: multivariate
    command: "gunicorn -w 4 -b 0.0.0.0:8070 app:server"
    restart: always
    ports:
      - "8070:8070"
    networks:
      - visualisation
networks:
  visualisation:
    name: spring_network
    external: true
