version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dataanalytics_dev3"
    volumes:
      # - ../db-schema/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      # - ../db-schema/02-setup-data.sql:/docker-entrypoint-initdb.d/02-setup-data.sql
      - dataanalytics-data:/var/lib/postgresql/data
    networks:
      - backend
  configserver:
    container_name: configserver
    image: theinnovativesolution/configserver:latest-dev
    ports:
      - "127.0.0.1:9071:9071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      - backend
  eurekaserver:
    container_name: eureka
    image: theinnovativesolution/eurekaserver:latest-dev
    ports:
      - "9070:9070"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      - backend
  gatewayserver:
    container_name: gateway
    image: theinnovativesolution/gatewayserver:latest-dev
    ports:
      - "9072:9072"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SERVER_PORT: "9072"
      CONFIGSERVER_URI: "http://configserver:9071"
      EUREKASERVER_URI: "http://eurekaserver:9070/eureka/"
      EUREKASERVER_PORT: "9070"
      CONFIGSERVER_PORT: "9071"
    depends_on:
      configserver:
        condition: service_started
      database:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - backend
  dataanalyticsservice:
    image: theinnovativesolution/dataanalytics:latest-dev
    container_name: dataanalytics
    env_file:
      - ./.env
    environment:
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:9071"
      CONFIGSERVER_PORT: "9071"
      DATABASESERVER_PORT: "6432"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      configserver:
        condition: service_started
      database:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    volumes:
      - /Innovativesolutions/Dataanalytics/data/:/Innovativesolutions/Dataanalytics/data/
    ports:
      - "5005:5005"
    networks:
      - backend
  registrataionservice:
    image: theinnovativesolution/authservice:latest-dev
    container_name: registration
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      CONFIGSERVER_URI: "http://configserver:9071"
      CONFIGSERVER_PORT: "9071"
      DATABASESERVER_PORT: "6432"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      configserver:
        condition: service_started
      database:
        condition: service_healthy
      eurekaserver:
        condition: service_started
    networks:
      - backend
networks:
  backend:
    name: spring_network
    driver: bridge
volumes:
  dataanalytics-data: