# Generated by Django 5.0.6 on 2024-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=225, verbose_name='Application Name')),
                ('source_branch', models.CharField(max_length=225, verbose_name='Source Branch')),
                ('build_tag', models.CharField(max_length=225, verbose_name='Tag')),
                ('build_status', models.CharField(choices=[('ST', 'Start'), ('PE', 'Pending'), ('SC', 'SUCCESS'), ('FL', 'FAILED')], max_length=225, verbose_name='Build Status')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
