# Generated by Django 5.0.6 on 2024-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdeploymenthistory',
            name='encryption_key',
            field=models.CharField(default=1, max_length=80, verbose_name='Encryption Key'),
            preserve_default=False,
        ),
    ]
