# Generated by Django 5.0.6 on 2024-05-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_engine', '0002_appdeploymenthistory_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdeploymenthistory',
            name='encryption_key',
        ),
    ]
