# Generated by Django 5.0.6 on 2024-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_engine', '0003_remove_appdeploymenthistory_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdeploymenthistory',
            name='pushed_at',
            field=models.CharField(default=4545, max_length=225, verbose_name='Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appdeploymenthistory',
            name='build_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Success', 'Success'), ('Failed', 'Failed')], max_length=225, verbose_name='Build Status'),
        ),
    ]
